### ISSUE TITLE
Rendering error

### ISSUE THREAD

**Issue by jackdeguest** [angels-Inc/black-static#13]
There is a discrepancy between the local version, ie without the css compressed and the optimised online version.
See the image attached.
The brand asset have a caption below which includes also an external link.
In the staged environment version, this is missing.
<img width="582" alt="css optimiser bug" src="https://user-images.githubusercontent.com/10134208/28137683-0e48e3e6-6789-11e7-8fbb-509ff3002c6d.png">

**Comment by fdidron** [comment]
@jackdeguest I can see the caption in staging can you confirm ?

**Comment by jackdeguest** [comment]
Nope still nothing.

**Comment by fdidron** [comment]
Did you deactivate any caching mechanism in our browser ?

**Comment by jackdeguest** [comment]
The problem is on my end, sorry.
