### ISSUE TITLE
Display problem with MS Edge

### ISSUE THREAD

**Issue by kaz6200** [angels-Inc/black-static#9]
![5](https://user-images.githubusercontent.com/30042141/28011224-8e088dfa-659c-11e7-8a65-b2342571a2b0.png)

need few lines between "エンジェルズインクのブラックエンジェルズ・メンバーシップにご興味をお持ち頂きありがとうございます" and "エンジェルズインクのブラックエンジェルズとは？"

**Comment by jackdeguest** [comment]
I fixed it by applying line-height 170% to the list, which was necessary not just for Windows Edge but for other as well to preserve visual consistency.
